### numpy - ndarray

In [7]:
import numpy as np
n_array = np.arange(10).reshape(2,5)
print(n_array)
print("ndim :", n_array.ndim, "shape :", n_array.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
ndim : 2 shape : (2, 5)


## Tensor

### pytorch - tensor

In [8]:
import torch
t_array =  torch.FloatTensor(n_array)
print(t_array)
print("ndim :", t_array.ndim, "shape :", t_array.shape)

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])
ndim : 2 shape : torch.Size([2, 5])


In [5]:
print(t_array.shape)
print(t_array.ndim)
print(t_array.size())

torch.Size([2, 5])
2
torch.Size([2, 5])


## Array to Tensor

### data to tensor

In [9]:
data = [[3, 5], [10, 5]]
x_data =torch.tensor(data)
x_data

tensor([[ 3,  5],
        [10,  5]])

### ndarray to tensor

In [10]:
nd_array_ex = np.array(data)
tensor_array = torch.from_numpy(nd_array_ex)
tensor_array

tensor([[ 3,  5],
        [10,  5]], dtype=torch.int32)

## numpy like operations

In [13]:
data = [[3, 5, 20],[10, 5, 50], [1, 5, 10]]
x_data = torch.tensor(data)

In [14]:
x_data[1:]

tensor([[10,  5, 50],
        [ 1,  5, 10]])

In [15]:
x_data[:2, 1:]

tensor([[ 5, 20],
        [ 5, 50]])

In [16]:
x_data.flatten()

tensor([ 3,  5, 20, 10,  5, 50,  1,  5, 10])

In [17]:
torch.ones_like(x_data)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [18]:
x_data.numpy()

array([[ 3,  5, 20],
       [10,  5, 50],
       [ 1,  5, 10]], dtype=int64)

In [20]:
x_data.shape

torch.Size([3, 3])

In [21]:
x_data.dtype

torch.int64

In [23]:
x_data.device

device(type='cpu')

In [25]:
if torch.cuda.is_available():
    x_data_cuda = x_data.to('cuda')
x_data_cuda.device

device(type='cuda', index=0)

## Tensor handling

In [26]:
tensor_ex = torch.rand(size = (2, 3, 2 ))
tensor_ex

tensor([[[0.8516, 0.2817],
         [0.9927, 0.6559],
         [0.0104, 0.5280]],

        [[0.4480, 0.1086],
         [0.5518, 0.7788],
         [0.8617, 0.6477]]])

In [27]:
tensor_ex.view([-1, 6])

tensor([[0.8516, 0.2817, 0.9927, 0.6559, 0.0104, 0.5280],
        [0.4480, 0.1086, 0.5518, 0.7788, 0.8617, 0.6477]])

In [28]:
tensor_ex.reshape([-1, 6])

tensor([[0.8516, 0.2817, 0.9927, 0.6559, 0.0104, 0.5280],
        [0.4480, 0.1086, 0.5518, 0.7788, 0.8617, 0.6477]])

In [30]:
a = torch.zeros(3, 2)
b = a.view(2, 3)
a.fill_(1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [31]:
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [32]:
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [34]:
a = torch.zeros(3, 2)
b = a.t().reshape(6)
a.fill_(1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [35]:
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [36]:
b

tensor([0., 0., 0., 0., 0., 0.])

In [37]:
tensor_ex = torch.rand(size =(2, 1, 2))
tensor_ex.squeeze()

tensor([[0.1397, 0.8764],
        [0.1493, 0.1878]])

In [38]:
tensor_ex = torch.rand(size=(2,2))
tensor_ex.unsqueeze(0).shape

torch.Size([1, 2, 2])

In [40]:
tensor_ex.unsqueeze(1).shape

torch.Size([2, 1, 2])

In [41]:
tensor_ex.unsqueeze(2).shape

torch.Size([2, 2, 1])

## Tensor operations

In [43]:
n1 = np.arange(10).reshape(2,5)
n2 = np.arange(10).reshape(5,2)
t1 = torch.FloatTensor(n1)
t2 = torch.FloatTensor(n2)

t1 + t1

tensor([[ 0.,  2.,  4.,  6.,  8.],
        [10., 12., 14., 16., 18.]])

In [44]:
t1 - t1

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [45]:
t1 +10

tensor([[10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])

In [46]:
t1.mm(t2)

tensor([[ 60.,  70.],
        [160., 195.]])

In [48]:
# 행렬곱은 mm 사용
#t1.dot(t2)

In [49]:
t1.matmul(t2)

tensor([[ 60.,  70.],
        [160., 195.]])

In [60]:
a = torch.rand(10)
b = torch.rand(10)

a.dot(b)

tensor(2.1631)

In [61]:
a = torch.rand(10)
b = torch.rand(10)

a.mm(b)

RuntimeError: self must be a matrix

In [62]:
a = torch.rand(5, 2, 3)
b = torch.rand(5)
a.mm(b)

RuntimeError: self must be a matrix

In [64]:
a = torch.rand(5, 2, 3)
b = torch.rand(3)
a.matmul(b)

tensor([[1.0527, 1.1209],
        [0.8265, 0.8631],
        [0.2879, 1.0912],
        [0.6800, 1.1905],
        [0.6364, 1.0630]])

In [71]:
a[0].mm(torch.unsqueeze(b,1)).squeeze()

tensor([1.0527, 1.1209])

In [72]:
a[1].mm(torch.unsqueeze(b,1))

tensor([[0.8265],
        [0.8631]])

In [73]:
a[2].mm(torch.unsqueeze(b,1))

tensor([[0.2879],
        [1.0912]])

In [74]:
a[3].mm(torch.unsqueeze(b,1))

tensor([[0.6800],
        [1.1905]])

In [75]:
a[4].mm(torch.unsqueeze(b,1))

tensor([[0.6364],
        [1.0630]])

## Tensor operations for ML/DL formula

In [77]:
import torch
import torch.nn.functional as F

tensor = torch.FloatTensor([0.5, 0.7, 0.1])
h_tensor = F.softmax(tensor, dim=0)
h_tensor

tensor([0.3458, 0.4224, 0.2318])

In [79]:
y = torch.randint(5, (10,5))
y_label = y.argmax(dim=1)
torch.nn.functional.one_hot(y_label)

tensor([[1, 0, 0, 0],
        [0, 0, 0, 1],
        [0, 1, 0, 0],
        [1, 0, 0, 0],
        [0, 0, 0, 1],
        [1, 0, 0, 0],
        [0, 0, 1, 0],
        [1, 0, 0, 0],
        [1, 0, 0, 0],
        [0, 0, 0, 1]])

In [81]:
import itertools
a = [1, 2, 3]
b = [4, 5]
list(itertools.product(a,b))

[(1, 4), (1, 5), (2, 4), (2, 5), (3, 4), (3, 5)]

In [83]:
tensor_a =torch.tensor(a)
tensor_b =torch.tensor(b)
torch.cartesian_prod(tensor_a, tensor_b)

tensor([[1, 4],
        [1, 5],
        [2, 4],
        [2, 5],
        [3, 4],
        [3, 5]])

## AutoCrad

In [86]:
w = torch.tensor(2.0, requires_grad = True)
y = w**2
z = 10*y +25
z.backward()
w.grad

tensor(40.)

In [89]:
a = torch.tensor([2., 3.], requires_grad = True)
b = torch.tensor([6., 4.], requires_grad = True)
Q =3*a**3 - b**2
external_grad = torch.tensor([1., 1.])
Q.backward(gradient = external_grad)

a.grad

tensor([36., 81.])

In [90]:
b.grad

tensor([-12.,  -8.])